# Generated by Django 4.2.11 on 2024-03-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_street_matatu_alter_evcharginglocation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matatu',
            name='fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
